export default [
  {
    name: "gallant_Idril",
    points: 5,
    state: "playing",
    roster: [
      {
        name: "",
        username: "jiji",
        surname: "",
        email: "",
        password: "",
        state: "playing",
        wristband: { id: 100, color: 2, state: "paired" },
      },
      {
        name: "",
        username: "noe",
        surname: "",
        email: "",
        password: "",
        state: "playing",
        wristband: { id: 93, color: 3, state: "paired" },
      },
    ],
    packages: [
      {
        id: 1,
        name: "Per Time 90",
        t_start: 1691387040323,
        t_end: null,
        cost: 150,
        type: "time",
        amount: 5400000,
        remainder: 5400000,
        state: "playing",
      },
    ],
  },
  {
    name: "pensive_Arwen",
    points: 10,
    state: "merged",
    roster: [
      {
        name: "",
        username: "8009ldtb0ph",
        surname: "",
        email: "",
        password: "",
        state: "inTeam",
        wristband: { id: 90, color: 3, state: "paired" },
      },
      {
        name: "",
        username: "5r5l24x8okh",
        surname: "",
        email: "",
        password: "",
        state: "inTeam",
        wristband: { id: 24, color: 5, state: "paired" },
      },
    ],
    packages: [],
  },
];
